import Head from 'next/head';
import AboutMe from '../components/AboutMe';
import NavBar from '../components/NavBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      <main>
        <AboutMe />
      </main>
    </div>
  );
}
